### ISSUE TITLE
NoMethodError: undefined method `default_header' for Unirest:Module

### ISSUE THREAD

**Issue by equivalent** [wondeltd/ruby-client#2]
```
client = Wonde::Client.new(ENV['WONDE_TOKEN'])

2.2.4 :008 > client.schools.all
NoMethodError: undefined method `default_header' for Unirest:Module
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/wondeclient-0.0.6/lib/endpoints.rb:136:in `_client'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/wondeclient-0.0.6/lib/endpoints.rb:37:in `getUrl'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/wondeclient-0.0.6/lib/endpoints.rb:29:in `getRequest'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/wondeclient-0.0.6/lib/endpoints.rb:125:in `all'
	from (irb):8
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/t/git/pobble/pobble.com/bin/rails:8:in `<top (required)>'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/commands/rails.rb:6:in `call'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/command_wrapper.rb:38:in `call'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:183:in `block in serve'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:156:in `fork'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:156:in `serve'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /home/t/.rvm/gems/ruby-2.2.4@pobblecom/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/t/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/t/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

  * wondeclient (0.0.6)
  * unirest (1.0.8)

**Comment by equivalent** [comment]
looks like you are not locking dependency to any particular version https://github.com/wondeltd/ruby-client/blob/master/WondeClient.gemspec#L14  (pessimistic locking  to maybe version `~> 1.1.2` ? as that is the latest one https://github.com/Mashape/unirest-ruby/blob/master/unirest.gemspec#L3 )

**Comment by equivalent** [comment]
...yep on fresh new irb when   Unirest version (1.1.2) is installed it works

**Comment by equivalent** [comment]
https://github.com/wondeltd/ruby-client/pull/4

**Comment by miked63017** [comment]
Merged, thx for the submission!
